//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTR_MED
    {
        public int MED_ID { get; set; }
        public string MED_LIB { get; set; }
        public string MED_CODE_CRT { get; set; }
        public int MED_DATREF { get; set; }
        public Nullable<int> XXX_TRT_ID { get; set; }
        public string XXX_CODE_MAJ { get; set; }
    }
}
